import { CompetitionType, EntitleType, Graduate, MemberInfo, Tier } from './../../interfaces/index'
import { AvatarType, PositionType } from '../../interfaces/index'

const data: MemberInfo[] = [
  {
    id: 1,
    name: 'SASAK',
    avatar: AvatarType.UNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 1,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 1,
        rank: 1,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 3,
        rank: 2,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 4,
        rank: 2
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 1
      },
    ],
    position: PositionType.SUBMASTER,
  },
  {
    id: 2,
    name: '바람',
    avatar: AvatarType.DIZNI,
    entitles: [],
    tier: Tier.NUMBER_TWO,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.ITEM_MATCH,
        season: 1,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 1,
        rank: 3,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 3,
        rank: 3,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 3,
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 1,
        rank: 1,
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 3,
        rank: 2,
      },
    ],
    position: PositionType.ELITE,
  },
  {
    id: 3,
    name: 'RIGEL',
    avatar: AvatarType.RABBIT,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 3,
        rank: 2,
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 1,
        rank: 3,
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 3,
        rank: 2,
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 4,
        rank: 2
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 4,
    name: 'JIZZANG',
    avatar: AvatarType.CHENCHEN,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.ITEM_MATCH,
        season: 3,
      },
      {
        title: CompetitionType.PUBLIC,
        season: 1,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 1,
        rank: 3,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 2,
        rank: 2,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 3,
        rank: 3,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
        rank: 2
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 3,
        rank: 1,
      },
      {
        title: CompetitionType.PUBLIC,
        season: 1,
        rank: 1,
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 5,
    name: 'RAMYEON',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.MASTER,
        season: 1,
      },
      {
        title: CompetitionType.MASTER,
        season: 3,
      },
      {
        title: CompetitionType.MASTER,
        season: 8,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 1,
        rank: 2,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 4,
        rank: 2
      },
      {
        title: CompetitionType.MASTER,
        season: 1,
        rank: 1,
      },
      {
        title: CompetitionType.MASTER,
        season: 3,
        rank: 1,
      },
      {
        title: CompetitionType.MASTER,
        season: 8,
        rank: 1,
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 6,
    name: '민뚜',
    avatar: AvatarType.UNI,
    entitles: [],
    tier: Tier.NUMBER_TWO,
    graduates: [Graduate.MASTER],
    trophys: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 2,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 4,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
      },
      {
        title: CompetitionType.MASTER,
        season: 9,
      },],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 1,
        rank: 3,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 2,
        rank: 1,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 3,
        rank: 3,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 4,
        rank: 1,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 1,
      },
      {
        title: CompetitionType.MASTER,
        season: 9,
        rank: 1,
      },
    ],
    position: PositionType.ELITE,
  },
  {
    id: 7,
    name: '주난',
    avatar: AvatarType.MARID,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.ITEM_MATCH,
        season: 2,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 2,
        rank: 3,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 3,
        rank: 3,
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 2,
        rank: 1,
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 8,
    name: 'LEGEND',
    avatar: AvatarType.RABBIT,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 2,
        rank: 2,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 3,
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 4,
        rank: 2
      }
    ],
    position: PositionType.MASTER,
  },
  {
    id: 9,
    name: '딴또',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 2,
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 3,
      },
      {
        title: CompetitionType.PUBLIC,
        season: 3,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 2,
        rank: 1,
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 3,
        rank: 1,
      },
      {
        title: CompetitionType.PUBLIC,
        season: 3,
        rank: 1,
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 10,
    name: '우주',
    avatar: AvatarType.BAZZI,
    entitles: [EntitleType.OFFICIAL_MATCH],
    tier: Tier.NUMBER_ONE,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 3,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 3,
        rank: 1,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 2,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
        rank: 1
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 2,
        rank: 3,
      },
    ],
    position: PositionType.ELITE,
  },
  {
    id: 11,
    name: 'TT',
    avatar: AvatarType.RABBIT,
    entitles: [EntitleType.ITEM_MATCH],
    tier: Tier.NUMBER_TWO,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.ITEM_MATCH,
        season: 4,
      },
      {
        title: CompetitionType.ELITE,
        season: 1,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 3,
        rank: 2,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
        rank: 2
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 4,
        rank: 1,
      },
      {
        title: CompetitionType.ELITE,
        season: 1,
        rank: 1,
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 12,
    name: 'ELLIS',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 13,
    name: '훈장',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 14,
    name: 'TAEYEON',
    avatar: AvatarType.CHENCHEN,
    entitles: [EntitleType.OFFICIAL_MATCH],
    tier: Tier.NUMBER_ONE,
    graduates: [Graduate.ELITE],
    trophys: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
      },
      {
        title: CompetitionType.ELITE,
        season: 4,
      },
      {
        title: CompetitionType.PUBLIC,
        season: 4,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 3,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
        rank: 1
      },
      {
        title: CompetitionType.ELITE,
        season: 4,
        rank: 1,
      },
      {
        title: CompetitionType.PUBLIC,
        season: 4,
        rank: 1,
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 15,
    name: '컴짱',
    avatar: AvatarType.RABBIT,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 1
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 16,
    name: '쫑쫑',
    avatar: AvatarType.DIZNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [Graduate.PUBLIC],
    trophys: [
      {
        title: CompetitionType.PUBLIC,
        season: 5,
      },
    ],
    records: [
      {
        title: CompetitionType.PUBLIC,
        season: 5,
        rank: 1,
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 17,
    name: 'LEVI',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 18,
    name: 'KNIFE',
    avatar: AvatarType.RABBIT,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 19,
    name: 'JAY',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 20,
    name: 'HARU',
    avatar: AvatarType.UNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 21,
    name: 'SUNGJIN',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 22,
    name: '밍공',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 23,
    name: 'KAIN',
    avatar: AvatarType.DIZNI,
    entitles: [],
    tier: Tier.NUMBER_ONE,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 24,
    name: '눈나시종',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_ONE,
    graduates: [],
    trophys: [],
    records: [
      {
        title: CompetitionType.ITEM_MATCH,
        season: 4,
        rank: 2
      }
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 25,
    name: 'SPET',
    avatar: AvatarType.CHENCHEN,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 26,
    name: 'QUATTRO',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 27,
    name: '와인',
    avatar: AvatarType.RABBIT,
    entitles: [EntitleType.OFFICIAL_MATCH],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 1
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
        rank: 1
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 28,
    name: 'ROA',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_TWO,
    graduates: [],
    trophys: [],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 3,
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 29,
    name: '치즈',
    avatar: AvatarType.CHENCHEN,
    entitles: [EntitleType.ITEM_MATCH],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.ITEM_MATCH,
        season: 4,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 3,
      },
      {
        title: CompetitionType.ITEM_MATCH,
        season: 4,
        rank: 1
      },
    ],
    position: PositionType.MEMBER,
  },
  { 
    id: 30,
    name: 'SUZY',
    avatar: AvatarType.RABBIT,
    entitles: [EntitleType.OFFICIAL_MATCH],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
      },
    ],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
        rank: 1
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 31,
    name: '영이',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 32,
    name: '눈나',
    avatar: AvatarType.BAZZI,
    entitles: [EntitleType.ITEM_MATCH],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [
      {
        title: CompetitionType.ITEM_MATCH,
        season: 4,
      },
    ],
    records: [
      {
        title: CompetitionType.ITEM_MATCH,
        season: 4,
        rank: 1,
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 33,
    name: 'HOPE',
    avatar: AvatarType.CHENCHEN,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 3,
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 34,
    name: 'SSOMACK',
    avatar: AvatarType.DIZNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 35,
    name: 'SULDOG',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 36,
    name: 'S',
    avatar: AvatarType.DIZNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 2,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
        rank: 2
      },
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 37,
    name: '찌니',
    avatar: AvatarType.UNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 5,
        rank: 3,
      },
      {
        title: CompetitionType.OFFICIAL_MATCH,
        season: 6,
        rank: 2
      },
    ],
    position: PositionType.ELITE,
  },
  {
    id: 38,
    name: '강철낙타',
    avatar: AvatarType.MARID,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [
      {
        title: CompetitionType.ITEM_MATCH,
        season: 4,
        rank: 2
      }
    ],
    position: PositionType.MEMBER,
  },
  {
    id: 39,
    name: 'CHAN',
    avatar: AvatarType.UNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 40,
    name: '짱돌',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  }, 
  {
    id: 41,
    name: '노을',
    avatar: AvatarType.CHENCHEN,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 42,
    name: '누나',
    avatar: AvatarType.DIZNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 43,
    name: '가을',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 44,
    name: '포돌S',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 45,
    name: '갱생빠따',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 46,
    name: 'HYUNNY',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 47,
    name: 'DDOK',
    avatar: AvatarType.ETHAN,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 48,
    name: '후니데디',
    avatar: AvatarType.UNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 49,
    name:'QUEEN',
    avatar: AvatarType.DIZNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 50,
    name: 'KING',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 51,
    name: 'OU',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 52,
    name: '참새',
    avatar: AvatarType.CHENCHEN,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 53,
    name: '나린아토',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 54,
    name: '가을',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 55,
    name: 'YUNJAM',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 56,
    name: 'ORI',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 57,
    name: '똘이',
    avatar: AvatarType.DIZNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 58,
    name: '경봉',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 59,
    name: '써니',
    avatar: AvatarType.RABBIT,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 60,
    name: '영주',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 61,
    name: 'SULHWA',
    avatar: AvatarType.ETHAN,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 62,
    name: 'LEOWATXH',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 63,
    name: '순조',
    avatar: AvatarType.ETHAN,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 64,
    name: 'SANGJA',
    avatar: AvatarType.DIZNI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 65,
    name: '햄니',
    avatar: AvatarType.MARID,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 66,
    name: 'MARIN',
    avatar: AvatarType.BAZZI,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
  {
    id: 67,
    name: 'DALVIT',
    avatar: AvatarType.DAO,
    entitles: [],
    tier: Tier.NUMBER_PUBLIC,
    graduates: [],
    trophys: [],
    records: [],
    position: PositionType.MEMBER,
  },
]

export default data
